apiVersion: batch/v1
kind: CronJob
metadata:
  name: tradingbot-aperanksimple-hourly
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tradingbot-aperanksimple-hourly
            image: guestros/tradingbot-aperanksimple:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: aperankhr
          restartPolicy: OnFailure
    