apiVersion: batch/v1
kind: CronJob
metadata:
  name: coingecko-gainers-24h-top100
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "5 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: coingecko-gainers-24h-top100
            image: guestros/tradingbot-coingecko-gainers:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: "cggain24h-top100"
              - name: COINGECKO_LOOKBACK
                value: "h24"
              - name: COINGECKO_TOP
                value: "100"
          restartPolicy: OnFailure