apiVersion: batch/v1
kind: CronJob
metadata:
  name: coingecko-gainers-1h-top300
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: coingecko-gainers-1h-top300
            image: guestros/tradingbot-coingecko-gainers:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: "cggain1h-top300"
              - name: COINGECKO_LOOKBACK
                value: "h1"
              - name: COINGECKO_TOP
                value: "300"
          restartPolicy: OnFailure