apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourlyupdate-cronjob
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trading-hourlyupdate
            image: alpine/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl -X 'GET' 'http://198.74.104.172:30002/update/hourly/'
          restartPolicy: OnFailure