apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trading
  labels:
    name: lstmlookbackhourly-pv-claim
  name: lstmlookbackhourly-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lstmlookback-retrain-hourly
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lstmlookback-retrain-hourly
            image: guestros/tradingbot-lstmlookback:latest
            imagePullPolicy: Always
            env:
              - name: SYMBOLS
                value: "ETHUSDT,AVAXUSDT,BNBUSDT,XRPUSDT"
              - name: BOTNAME
                value: "LSTMsimple"
            volumeMounts:
              - name: lstmlookbackhourly
                mountPath: /results/
          restartPolicy: OnFailure
          volumes:
            - name: lstmlookbackhourly
              persistentVolumeClaim:
                claimName: lstmlookbackhourly-pv-claim