apiVersion: batch/v1
kind: CronJob
metadata:
  name: cryptoqualitysignalbotandupdater
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cryptoqualitysignalbotandupdater
            image: guestros/tradingbot-cryptoqualitysignalsbot-and-updater:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: "SIG-CQS-LONG"
              - name: QUERY_API
                value: "true"
              - name: BUY_WAITFORMID
                value: "true"
              - name: SIGNAL_LOOKBACK
                value: "1" # days
              - name: PSQL_URL
                valueFrom:
                  secretKeyRef:
                    name: binance-creds
                    key: PSQL_URL
              - name: CQS_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: cryptoqualitysignals 
                    key: CQS_API_KEY
          restartPolicy: OnFailure