apiVersion: batch/v1
kind: CronJob
metadata:
  name: simplesmacross-hourly
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simplesmacross-hourly
            image: guestros/tradingbot-simplesma-goldencross:latest
            imagePullPolicy: Always
            env:
              - name: SYMBOLS
                value: "ETHUSDT,AVAXUSDT,BNBUSDT,XRPUSDT"
          restartPolicy: OnFailure