apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trading
  labels:
    name: xgb-minmax-daily-pv-claim
  name: xgb-minmax-daily-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xgb-minmax-daily
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "1 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: xgb-minmax-daily
            image: guestros/tradingbot-xgb-minmax-30min:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: "xgbdaily"
              - name: LOOKBACK_TRAINING
                value: "1y"
              - name: LOOKBACK_PREDICTION
                value: "14d"
              - name: INTERVAL
                value: "1d"
              - name: LOOKBACK_MEDIAN_PRED
                value: "1"
            volumeMounts:
              - name: xgb-minmax-daily-pv
                mountPath: /persistent/
          restartPolicy: OnFailure
          volumes:
            - name: xgb-minmax-daily-pv
              persistentVolumeClaim:
                claimName: xgb-minmax-daily-pv-claim