apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trading
  labels:
    name: xgb-minmax-30min-3stepbuffer-pv-claim
  name: xgb-minmax-30min-3stepbuffer-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xgb-minmax-30min-3stepbuffer
  namespace: trading
spec:
  concurrencyPolicy: "Forbid"
  schedule: "31,1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: xgb-minmax-30min-3stepbuffer
            image: guestros/tradingbot-xgb-minmax-30min:latest
            imagePullPolicy: Always
            env:
              - name: BOTNAME
                value: "xgb30buff"
              - name: LOOKBACK_TRAINING
                value: "60d"
              - name: LOOKBACK_PREDICTION
                value: "2d"
              - name: INTERVAL
                value: "30m"
              - name: LOOKBACK_MEDIAN_PRED
                value: "3"
            volumeMounts:
              - name: xgb-minmax-30min-3stepbuffer-pv
                mountPath: /persistent/
          restartPolicy: OnFailure
          volumes:
            - name: xgb-minmax-30min-3stepbuffer-pv
              persistentVolumeClaim:
                claimName: xgb-minmax-30min-3stepbuffer-pv-claim