apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trading
  labels:
    name: lstm-recenttrades-retrain-pv-claim
  name: lstm-recenttrades-retrain-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lstm-recenttrades-retrain
  name: lstm-recenttrades-retrain
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lstm-recenttrades-retrain
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: lstm-recenttrades-retrain
    spec:
      containers:
        - env:
            - name: SYMBOLS
              value: "AVAXUSDT"
            - name: BOTNAME
              value: "lstmrecent"
          image: guestros/tradingbot-recentrades-lstm:latest
          name: lstm-recenttrades-retrain
          resources: {}
          volumeMounts:
              - name: lstm-recenttrades-retrain-pv
                mountPath: /results/
      restartPolicy: Always
      volumes:
            - name: lstm-recenttrades-retrain-pv
              persistentVolumeClaim:
                claimName: lstm-recenttrades-retrain-pv-claim
status: {}