version: "3"
services:
  accounthandler:
    image: guestros/tradingbot-accounthandler:latest
    build: ./accounthandler
    ports:
      - "8000:8000"
    environment:
      - SYMBOLS="BTC,ETH"
      - STOCKS="AAPL,TSLA"
    env_file:
      - .env
    # restart: on-failuredoc