version: "3"
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - tradingbot-mongodbdata:/data/db

  tradingbot-acchandler:
    image: guestros/tradingbot-accounthandler:latest
    build: ./accounthandler/
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
    #   - BINANCE_KEY=2222
    #   - BINANCE_SECRET=2222
    #   - SECRET=222
    - MONGODB_HOST=mongodb

volumes:
  tradingbot-mongodbdata: