apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: trading
  labels:
    name: sklearn-recenttrades-pv-claim
  name: sklearn-recenttrades-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sklearn-recenttrades
  name: sklearn-recenttrades
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sklearn-recenttrades
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: sklearn-recenttrades
    spec:
      containers:
        - env:
            # - name: SYMBOLS
            #   value: "AVAXUSDT"
            - name: BOTNAME
              value: "recentsk"
          image: guestros/tradingbot-recenttrades-sklearn:latest
          name: sklearn-recenttrades
          resources: {}
          volumeMounts:
              - name: sklearn-recenttrades-pv
                mountPath: /results/
      restartPolicy: Always
      volumes:
            - name: sklearn-recenttrades-pv
              persistentVolumeClaim:
                claimName: sklearn-recenttrades-pv-claim
status: {}