apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: trading
  labels:
    service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana-oss:latest
          name: grafana
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: 15m
            limits:
              memory: "200Mi"
              cpu: 100m
          # volumeMounts:
          #   - mountPath: /app/grafana_home/
          #     name: grafana-v
      restartPolicy: Always
      # volumes:
      #   - name: grafana-v
      #     persistentVolumeClaim:
      #       claimName: grafana-vc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  namespace: trading
  name: grafana-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
  selector:
    app: grafana

