apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: recenttrades-ingestor
  name: recenttrades-ingestor
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recenttrades-ingestor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: recenttrades-ingestor
    spec:
      containers:
        - env:
            - name: PSQL_URL
              valueFrom:
                configMapKeyRef:
                  key: PSQL_URL
                  name: env
          image: guestros/tradingbot-recenttrades-ingestor:latest
          name: recenttrades-ingestor
          resources: {}
      restartPolicy: Always
status: {}