---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prefect
  labels:
    app: prefect-agent
  name: prefect-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - args:
        - prefect agent kubernetes start
        command:
        - /bin/bash
        - -c
        env:
        # - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
        #   value: ''
        - name: PREFECT__CLOUD__API
          value: https://api.prefect.io
        - name: NAMESPACE
          value: trading
        # - name: IMAGE_PULL_SECRETS
        #   value: ''
        # - name: PREFECT__CLOUD__AGENT__LABELS
        #   value: '[]'
        # - name: JOB_MEM_REQUEST
        #   value: ''
        # - name: JOB_MEM_LIMIT
        #   value: ''
        # - name: JOB_CPU_REQUEST
        #   value: ''
        # - name: JOB_CPU_LIMIT
        #   value: ''
        - name: IMAGE_PULL_POLICY
          value: 'Always'
        # - name: SERVICE_ACCOUNT_NAME
        #   value: ''
        - name: PREFECT__BACKEND
          value: cloud
        # - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
        #   value: http://:8080
        - name: PREFECT__CLOUD__API_KEY
          valueFrom:
            secretKeyRef:
              name: prefectkey
              key: prefectkey
        # - name: PREFECT__CLOUD__TENANT_ID
        #   value: ''
        image: prefecthq/prefect:1.2.0-python3.7
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        name: agent

